### ISSUE TITLE
Exchange perfomance

### ISSUE THREAD

**Issue by z0mb1ek** [rabbitmq/rabbitmq-consistent-hash-exchange#34]
Hi. If I understand correctly if add more nodes to my cluster will I get more perfomance on my consistence hash exchange? thx

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
It doesn't matter how many nodes you have to this exchange (and in many other cases).

You may be confusing this plugin with [rabbitmq-sharding](http://github.com/rabbitmq/rabbitmq-sharding/) with which adding more nodes and distributing consumers between will improve total throughput.

See a section on resource utilisation in the [Queues guide](http://www.rabbitmq.com/queues.html) as well.

**Comment by z0mb1ek** [comment]
can you say, please, has exchange any throughput max or it depends on how many queues it has?

**Comment by michaelklishin** [comment]
Exchanges do not actually exist. They are just named routing tables, channels do the routing. Obviously there is a certain limit to how quickly a channel can do it but it is not artificially limited.

The number of bindings may or may not matter depending on what an exchange does. With this exchange it in particular the effect from increasing the number of bindings should be moderate but as with any other "scalability with respect to X" question, don't listen to people on the Internet: do your own benchmarking and algorithm analysis.

Routing a message to N queues will be roughly N times slower than to 1 queue. Routing to queues
is subject to [credit flow-based throttling](http://alvaro-videla.com/2013/09/rabbitmq-internals-credit-flow-for-erlang-processes.html), which is typically the limiting factor as the rest of
routing does not involve potentially going over the network and such.

Unlike topic exchange, for instance, this exchange hasn't been particularly optimised because it's nowhere near as widely used. rabbitmq-sharding has a similar exchange type so every user of that plugin does not need this exchange.

**Comment by michaelklishin** [comment]
All further discussions belong to the mailing list.
